# 01_multi_head_attention
先阅读对应讲解，预测形状后运行。修改参数，再写下观察。

In [1]:
from pathlib import Path
import sys
root = Path.cwd().resolve()
while not (root / "exercises/week03/block_utils.py").exists():
    if root == root.parent:
        raise RuntimeError("请在 ai_basic 项目中启动 Notebook")
    root = root.parent
sys.path.insert(0, str(root / "exercises/week03"))


In [2]:
from block_utils import X, multi_head, show
import numpy as np

out, weights, concat = multi_head(X)
show("X", X)
for i, a in enumerate(weights):
    show(f"head {i+1} weights", a)
    np.testing.assert_allclose(a.sum(axis=-1), 1.)
show("concat", concat)
show("output", out)
assert out.shape == X.shape


X shape=(3, 4)
[[1. 0. 0. 1.]
 [0. 1. 0. 1.]
 [1. 1. 0. 0.]]

head 1 weights shape=(3, 3)
[[0.19279944 0.61612938 0.19107118]
 [0.34078063 0.38997011 0.26924926]
 [0.13561262 0.67330999 0.1910774 ]]

head 2 weights shape=(3, 3)
[[0.32854564 0.36245417 0.30900019]
 [0.34701624 0.31413586 0.3388479 ]
 [0.31442237 0.26952804 0.41604959]]

concat shape=(3, 4)
[[ 0.55962384 -0.26461928  0.33954954  0.09613234]
 [ 0.52948418 -0.25857381  0.331397    0.10870138]
 [ 0.57050778 -0.26373219  0.28712515  0.08408713]]

output shape=(3, 4)
[[-0.05033092 -0.14918282  0.03339307 -0.02854877]
 [-0.06024199 -0.15273474  0.0282537  -0.01707457]
 [-0.04618903 -0.09213579  0.02259544 -0.04680975]]



In [8]:
rng_1 = np.random.default_rng(3)

g=rng_1.normal(0, .4, (4, 2))
print(rng_1)
print(g.shape)
print(g)

Generator(PCG64)
(4, 2)
[[ 0.81636765 -1.02226601]
 [ 0.16723954 -0.22710784]
 [-0.18105972 -0.08623887]
 [-0.80799445 -0.09277295]]


## 我的解释
运行前预测：

实际观察：

原因与疑问：