# 03_ffn_residual_layernorm
先阅读对应讲解，预测形状后运行。修改参数，再写下观察。

In [1]:
from pathlib import Path
import sys
root = Path.cwd().resolve()
while not (root / "exercises/week03/block_utils.py").exists():
    if root == root.parent:
        raise RuntimeError("请在 ai_basic 项目中启动 Notebook")
    root = root.parent
sys.path.insert(0, str(root / "exercises/week03"))


In [2]:
from block_utils import X, layer_norm, ffn, show
import numpy as np

normalized = layer_norm(X)
show("LayerNorm(X)", normalized)
print("每行均值:", normalized.mean(axis=-1))
print("每行方差:", normalized.var(axis=-1))
show("FFN(X)", ffn(X))
show("X + FFN(X)", X + ffn(X))
changed = X.copy()
changed[0] += [1., -1., 2., 0.]
np.testing.assert_allclose(ffn(changed)[1:], ffn(X)[1:])
print("只修改第一行：FFN 其他行保持不变")


LayerNorm(X) shape=(3, 4)
[[ 0.99998 -0.99998 -0.99998  0.99998]
 [-0.99998  0.99998 -0.99998  0.99998]
 [ 0.99998  0.99998 -0.99998 -0.99998]]

每行均值: [0. 0. 0.]
每行方差: [0.99996 0.99996 0.99996]
FFN(X) shape=(3, 4)
[[ 0.00271604 -0.06855657  0.03393779 -0.18623606]
 [ 0.00122953  0.00208925  0.01137119 -0.05224473]
 [ 0.06964242 -0.1453921   0.00627937 -0.3873608 ]]

X + FFN(X) shape=(3, 4)
[[ 1.00271604 -0.06855657  0.03393779  0.81376394]
 [ 0.00122953  1.00208925  0.01137119  0.94775527]
 [ 1.06964242  0.8546079   0.00627937 -0.3873608 ]]

只修改第一行：FFN 其他行保持不变


In [3]:
print("ffn(changed):\n",ffn(changed))
print("ffn(X):\n",ffn(X))

ffn(changed):
 [[ 0.06602372 -0.1355712   0.03092878 -0.39145101]
 [ 0.00122953  0.00208925  0.01137119 -0.05224473]
 [ 0.06964242 -0.1453921   0.00627937 -0.3873608 ]]
ffn(X):
 [[ 0.00271604 -0.06855657  0.03393779 -0.18623606]
 [ 0.00122953  0.00208925  0.01137119 -0.05224473]
 [ 0.06964242 -0.1453921   0.00627937 -0.3873608 ]]


## 我的解释
运行前预测：

实际观察：

原因与疑问：

In [4]:
X1=np.array([1.0,2.0,3.0,4.0])
X2=np.array([11.0,12.0,13.0,14.0])
x1_normalized = layer_norm(X1)
show("LayerNorm(X1)", x1_normalized)

x2_normalized = layer_norm(X2)
show("LayerNorm(X1)", x2_normalized)

LayerNorm(X1) shape=(4,)
[-1.34163542 -0.44721181  0.44721181  1.34163542]

LayerNorm(X1) shape=(4,)
[-1.34163542 -0.44721181  0.44721181  1.34163542]

