# 02 概率与 softmax。


In [3]:
import numpy as np

scores = np.array([2.0,1.0,0.0])
exp_scores = np.exp(scores)

print("exp_scores \n",exp_scores)
probabilities = exp_scores / exp_scores.sum()

print(probabilities)
print(probabilities.sum())

exp_scores 
 [7.3890561  2.71828183 1.        ]
[0.66524096 0.24472847 0.09003057]
1.0


In [7]:
scores_2 = np.array([2, 2, 2])
exp_scores_2 = np.exp(scores_2)

print("scores_2 \n",exp_scores_2)
probabilities_2 = exp_scores_2 / exp_scores_2.sum()

print(probabilities_2)
print(probabilities_2.sum())

scores_2 
 [7.3890561 7.3890561 7.3890561]
[0.33333333 0.33333333 0.33333333]
1.0


In [11]:
target =2
loss = - np.log(probabilities[target])
print("loss:",loss)

loss: 2.40760596444438


In [13]:
model_a = np.array([0.1,0.8,0.1])
model_b = np.array([0.3,0.4,0.3])
exp_score_a = np.exp(model_a)
exp_score_b = np.exp(model_b)

probabilities_a = exp_score_a / exp_score_a.sum()
probabilities_b = exp_score_b / exp_score_b.sum()


softmax_a=- np.log(probabilities_a[1])
softmax_b=- np.log(probabilities_b[1])

print("softmax_a:",softmax_a)
print("softmax_b:",softmax_b)

softmax_a: 0.6897266409702164
softmax_b: 1.0330687599495758


## - 把已有概率又做了一次 softmax。
- 第二个选项应使用索引 1，而不是 0。
  
a = np.array([0.1, 0.8, 0.1])
b = np.array([0.3, 0.4, 0.3])
target = 1

print(-np.log(a[target]))
print(-np.log(b[target]))