# 第二周第 1 课

先阅读 [课程讲解](../../docs/week02/01_tokens_and_embeddings.md)。运行前先预测形状与变化，然后从上到下运行。


In [1]:
from pathlib import Path
import sys

# 支持从项目根目录或 Notebook 所在目录启动。
root = next(p for p in (Path.cwd(), *Path.cwd().parents)
            if (p / "exercises/week02/attention_utils.py").exists())
sys.path.insert(0, str(root / "exercises/week02"))
import numpy as np
np.set_printoptions(precision=4, suppress=True)


In [2]:
import runpy
experiment = runpy.run_path(str(root / "exercises/week02/01_tokens_and_embeddings.py"))
globals().update({k: v for k, v in experiment.items() if not k.startswith("__")})


tokens: ['我', '喜欢', '学习']
ids shape=(3,)
[0 1 2]

X shape=(3, 4)
[[1. 0. 0. 1.]
 [0. 1. 0. 1.]
 [0. 0. 1. 1.]]

重复 token 的输入向量相同: True


In [3]:
# 修改文本后重新查表，比较形状与对应行。
my_text = "你 喜欢 学习"
my_tokens, my_ids, my_X = embed(my_text)
print(my_tokens, my_ids)
print(my_X)


['你', '喜欢', '学习'] [3 1 2]
[[1. 1. 0. 0.]
 [0. 1. 0. 1.]
 [0. 0. 1. 1.]]


## 学习记录

- 我运行前的预测：
- 我修改了什么：
- 实际观察：
- 我能解释的原因与剩余疑问：

完成后记录到 `progress/week02.md`。
