# 第二周第 2 课

先阅读 [课程讲解](../../docs/week02/02_qkv.md)。运行前先预测形状与变化，然后从上到下运行。


In [1]:
from pathlib import Path
import sys

# 支持从项目根目录或 Notebook 所在目录启动。
root = next(p for p in (Path.cwd(), *Path.cwd().parents)
            if (p / "exercises/week02/attention_utils.py").exists())
sys.path.insert(0, str(root / "exercises/week02"))
import numpy as np
np.set_printoptions(precision=4, suppress=True)


In [3]:
import runpy
experiment = runpy.run_path(str(root / "exercises/week02/02_qkv.py"))
globals().update({k: v for k, v in experiment.items() if not k.startswith("__")})


Wq shape=(4, 2)
[[1. 0.]
 [0. 1.]
 [1. 1.]
 [0. 0.]]

Wk shape=(4, 2)
[[ 1.  0.]
 [ 0.  1.]
 [ 1. -1.]
 [ 0.  0.]]

Wv shape=(4, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 1. 1.]]

X shape=(3, 4)
[[1. 0. 0. 1.]
 [0. 1. 0. 1.]
 [0. 0. 1. 1.]]

Q shape=(3, 2)
[[1. 0.]
 [0. 1.]
 [1. 1.]]

K shape=(3, 2)
[[ 1.  0.]
 [ 0.  1.]
 [ 1. -1.]]

V shape=(3, 3)
[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]

O shape=(3, 3)
[[1.4011 1.1978 1.4011]
 [1.284  1.576  1.14  ]
 [1.4011 1.4011 1.1978]]



## 学习记录

- 我运行前的预测：
- 我修改了什么：
- 实际观察：
- 我能解释的原因与剩余疑问：

完成后记录到 `progress/week02.md`。
