# 第二周第 4 课

先阅读 [课程讲解](../../docs/week02/04_attention_experiments.md)。运行前先预测形状与变化，然后从上到下运行。


In [1]:
from pathlib import Path
import sys

# 支持从项目根目录或 Notebook 所在目录启动。
root = next(p for p in (Path.cwd(), *Path.cwd().parents)
            if (p / "exercises/week02/attention_utils.py").exists())
sys.path.insert(0, str(root / "exercises/week02"))
import numpy as np
np.set_printoptions(precision=4, suppress=True)


In [2]:
import runpy
experiment = runpy.run_path(str(root / "exercises/week02/04_attention_experiments.py"))
globals().update({k: v for k, v in experiment.items() if not k.startswith("__")})


Q 差值 shape=(3, 2)
[[0. 0.]
 [0. 0.]
 [1. 0.]]

K 差值 shape=(3, 2)
[[0. 0.]
 [0. 0.]
 [1. 0.]]

V 差值 shape=(3, 3)
[[0. 0. 0.]
 [0. 0. 0.]
 [1. 0. 0.]]

scores 差值 shape=(3, 3)
[[0.     0.     0.7071]
 [0.     0.     0.    ]
 [0.7071 0.     2.1213]]

A 差值 shape=(3, 3)
[[-0.1171 -0.0577  0.1749]
 [ 0.      0.      0.    ]
 [-0.1171 -0.2611  0.3782]]

O 差值 shape=(3, 3)
[[ 0.4589 -0.0577  0.1749]
 [ 0.14    0.      0.    ]
 [ 0.4589 -0.2611  0.3782]]

只修改 V 时的输出差值 shape=(3, 3)
[[0.4011 0.     0.    ]
 [0.14   0.     0.    ]
 [0.1978 0.     0.    ]]

只修改 Q 时的权重差值 shape=(3, 3)
[[ 0.0447 -0.0894  0.0447]
 [ 0.      0.      0.    ]
 [ 0.      0.      0.    ]]

对照实验核对通过


## 学习记录

- 我运行前的预测：
- 我修改了什么：
- 实际观察：
- 我能解释的原因与剩余疑问：

完成后记录到 `progress/week02.md`。
